# Generated by Django

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('openai_base_url', models.URLField(blank=True)),
                ('openai_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('whisper_model', models.CharField(default='base', max_length=50)),
                ('whisper_device', models.CharField(choices=[('auto', '自动选择'), ('cuda', 'GPU (CUDA)'), ('cpu', 'CPU')], default='auto', max_length=10)),
                ('auto_load_model', models.BooleanField(default=False, help_text='启用后，有任务时自动加载模型，任务完成后自动卸载模型以节省显存')),
                ('summary_prompt', models.TextField(default='总结录音，简体中文回答')),
                ('url_summary_prompt', models.TextField(default='本次录音的标题是{title}, 简要回答标题的问题，并且总结录音，简体中文回答')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('task_type', models.CharField(choices=[('url', 'URL视频'), ('file', '文件上传')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('downloading', '下载中'), ('transcribing', '转录中'), ('summarizing', '总结中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('original_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '视频任务',
                'verbose_name_plural': '视频任务',
                'ordering': ['-created_at'],
            },
        ),
    ]