# Generated by Django 4.2.7 on 2025-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="url_summary_prompt",
            field=models.TextField(
                default="- 本次录音的标题是{title}, 简要回答标题的问题，并且总结录音，简体中文回答 - 标准MarkDown格式输出，使用有序无序列表，有层次的回答，使用横线分隔不同层次的内容 - 使用 > 回答标题问题，并且一句话总结，然后总结录音内容"
            ),
        ),
        migrations.AlterField(
            model_name="videotask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "排队中"),
                    ("downloading", "下载中"),
                    ("transcribing", "转录中"),
                    ("summarizing", "总结中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videotask",
            name="task_type",
            field=models.CharField(
                choices=[("url", "URL视频"), ("file", "上传文件")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="videotask",
            name="video_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
